# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Cache
version:      1.12
version_from: lib/Class/Cache.pm
installdirs:  site
requires:
    Class::Prototyped:             1.1
    Params::Validate:              0.78
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
